# Site settings
title: Fundamentals of Web Development
email: bmiller@luther.edu
description: "Notes and Syllabus for Fundamentals of Web Development"
baseurl: "http://bnmnetp.github.io/CS130/"
url: "http://bnmnetp.github.io"
twitter_username: bnmnetp
github_username:  bnmnetp

# Build settings
permalink: pretty
